version: 2.1
orbs:
  architect: giantswarm/architect@0.4.3

commands:
  package-chart:
    description: "Helm package"
    parameters:
      chart:
        type: string
      destination:
        type: string
    steps:
      - checkout
      - run:
          name: Package Chart
          command: 'helm package ./helm/<< chart >> -d ./helm/<< destination >>/charts'

jobs:
  package-child-charts:
    steps:
      - package-chart:
          chart: "efk-logging-curator"
          destination: "efk-logging-stack"
      - package_chart:
          chart: "efk-logging-fluentd"
          destination: "efk-logging-stack"
      - package_chart:
          chart: "efk-logging-kibana"
          destination: "efk-logging-stack"
      - package_chart:
          chart: "efk-logging-elasticsearch"
          destination: "efk-logging-stack"

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - package-child-charts:
          name: "Package child charts"

      - architect/push-to-app-catalog:
          name: "Package and push EFK Stack chart"
          app_catalog: "giantswarm-incubator-catalog"
          app_catalog_test: "giantswarm-incubator-test-catalog"
          chart: "efk-logging-stack"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - "Package child charts"