version: 2.1
orbs:
  architect: giantswarm/architect@0.4.5
          
workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "Package and push EFK Stack chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "efk-logging-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/