elasticsearch:
  enabled: true
  # for options see https://github.com/giantswarm/helm-elasticsearch

kibana:
  enabled: false
  # for options see https://github.com/giantswarm/helm-kibana

fluentd:
  enabled: true
  # for options see https://github.com/helm/charts/blob/master/stable/fluentd-elasticsearch

elasticsearch-curator:
  enabled: true
  # for options see https://github.com/helm/charts/tree/master/stable/elasticsearch-curator

elasticsearch-exporter:
  enabled: true
  # for options see https://github.com/helm/charts/tree/master/stable/elasticsearch-exporter